//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Original file name: ZGWSAMPLE_SRV.cs
// Generation date: 5/30/2014 6:10:55 PM
namespace AdnWebAPI.ZGWSAMPLE_SRV{
    
    /// <summary>
    /// There are no comments for ZGWSAMPLE_SRV in the schema.
    /// </summary>
    public partial class ZGWSAMPLE_SRV : global::System.Data.Services.Client.DataServiceContext
    {
        /// <summary>
        /// Initialize a new ZGWSAMPLE_SRV object.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public ZGWSAMPLE_SRV(global::System.Uri serviceRoot) : 
                base(serviceRoot)
        {
            this.OnContextCreated();
        }
        partial void OnContextCreated();
        /// <summary>
        /// There are no comments for SalesOrderLineItemCollection in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceQuery<SalesOrderLineItem> SalesOrderLineItemCollection
        {
            get
            {
                if ((this._SalesOrderLineItemCollection == null))
                {
                    this._SalesOrderLineItemCollection = base.CreateQuery<SalesOrderLineItem>("SalesOrderLineItemCollection");
                }
                return this._SalesOrderLineItemCollection;
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceQuery<SalesOrderLineItem> _SalesOrderLineItemCollection;
        /// <summary>
        /// There are no comments for BusinessPartnerCollection in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceQuery<BusinessPartner> BusinessPartnerCollection
        {
            get
            {
                if ((this._BusinessPartnerCollection == null))
                {
                    this._BusinessPartnerCollection = base.CreateQuery<BusinessPartner>("BusinessPartnerCollection");
                }
                return this._BusinessPartnerCollection;
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceQuery<BusinessPartner> _BusinessPartnerCollection;
        /// <summary>
        /// There are no comments for ContactCollection in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceQuery<Contact> ContactCollection
        {
            get
            {
                if ((this._ContactCollection == null))
                {
                    this._ContactCollection = base.CreateQuery<Contact>("ContactCollection");
                }
                return this._ContactCollection;
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceQuery<Contact> _ContactCollection;
        /// <summary>
        /// There are no comments for SalesOrderCollection in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceQuery<SalesOrder> SalesOrderCollection
        {
            get
            {
                if ((this._SalesOrderCollection == null))
                {
                    this._SalesOrderCollection = base.CreateQuery<SalesOrder>("SalesOrderCollection");
                }
                return this._SalesOrderCollection;
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceQuery<SalesOrder> _SalesOrderCollection;
        /// <summary>
        /// There are no comments for ProductCollection in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceQuery<Product> ProductCollection
        {
            get
            {
                if ((this._ProductCollection == null))
                {
                    this._ProductCollection = base.CreateQuery<Product>("ProductCollection");
                }
                return this._ProductCollection;
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceQuery<Product> _ProductCollection;
        /// <summary>
        /// There are no comments for SalesOrderLineItemCollection in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public void AddToSalesOrderLineItemCollection(SalesOrderLineItem salesOrderLineItem)
        {
            base.AddObject("SalesOrderLineItemCollection", salesOrderLineItem);
        }
        /// <summary>
        /// There are no comments for BusinessPartnerCollection in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public void AddToBusinessPartnerCollection(BusinessPartner businessPartner)
        {
            base.AddObject("BusinessPartnerCollection", businessPartner);
        }
        /// <summary>
        /// There are no comments for ContactCollection in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public void AddToContactCollection(Contact contact)
        {
            base.AddObject("ContactCollection", contact);
        }
        /// <summary>
        /// There are no comments for SalesOrderCollection in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public void AddToSalesOrderCollection(SalesOrder salesOrder)
        {
            base.AddObject("SalesOrderCollection", salesOrder);
        }
        /// <summary>
        /// There are no comments for ProductCollection in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public void AddToProductCollection(Product product)
        {
            base.AddObject("ProductCollection", product);
        }
    }
    /// <summary>
    /// There are no comments for ZGWSAMPLE_SRV.SalesOrderLineItem in the schema.
    /// </summary>
    /// <KeyProperties>
    /// SoId
    /// SoItemPos
    /// </KeyProperties>
    [global::System.Data.Services.Common.EntitySetAttribute("SalesOrderLineItemCollection")]
    [global::System.Data.Services.Common.DataServiceKeyAttribute("SoId", "SoItemPos")]
    public partial class SalesOrderLineItem : global::System.ComponentModel.INotifyPropertyChanged
    {
        /// <summary>
        /// Create a new SalesOrderLineItem object.
        /// </summary>
        /// <param name="soId">Initial value of SoId.</param>
        /// <param name="soItemPos">Initial value of SoItemPos.</param>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public static SalesOrderLineItem CreateSalesOrderLineItem(string soId, string soItemPos)
        {
            SalesOrderLineItem salesOrderLineItem = new SalesOrderLineItem();
            salesOrderLineItem.SoId = soId;
            salesOrderLineItem.SoItemPos = soItemPos;
            return salesOrderLineItem;
        }
        /// <summary>
        /// There are no comments for Property SoId in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string SoId
        {
            get
            {
                return this._SoId;
            }
            set
            {
                this.OnSoIdChanging(value);
                this._SoId = value;
                this.OnSoIdChanged();
                this.OnPropertyChanged("SoId");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _SoId;
        partial void OnSoIdChanging(string value);
        partial void OnSoIdChanged();
        /// <summary>
        /// There are no comments for Property SoItemPos in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string SoItemPos
        {
            get
            {
                return this._SoItemPos;
            }
            set
            {
                this.OnSoItemPosChanging(value);
                this._SoItemPos = value;
                this.OnSoItemPosChanged();
                this.OnPropertyChanged("SoItemPos");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _SoItemPos;
        partial void OnSoItemPosChanging(string value);
        partial void OnSoItemPosChanged();
        /// <summary>
        /// There are no comments for Property ProductId in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string ProductId
        {
            get
            {
                return this._ProductId;
            }
            set
            {
                this.OnProductIdChanging(value);
                this._ProductId = value;
                this.OnProductIdChanged();
                this.OnPropertyChanged("ProductId");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _ProductId;
        partial void OnProductIdChanging(string value);
        partial void OnProductIdChanged();
        /// <summary>
        /// There are no comments for Property Note in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Note
        {
            get
            {
                return this._Note;
            }
            set
            {
                this.OnNoteChanging(value);
                this._Note = value;
                this.OnNoteChanged();
                this.OnPropertyChanged("Note");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Note;
        partial void OnNoteChanging(string value);
        partial void OnNoteChanged();
        /// <summary>
        /// There are no comments for Property CurrencyCode in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string CurrencyCode
        {
            get
            {
                return this._CurrencyCode;
            }
            set
            {
                this.OnCurrencyCodeChanging(value);
                this._CurrencyCode = value;
                this.OnCurrencyCodeChanged();
                this.OnPropertyChanged("CurrencyCode");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _CurrencyCode;
        partial void OnCurrencyCodeChanging(string value);
        partial void OnCurrencyCodeChanged();
        /// <summary>
        /// There are no comments for Property GrossAmount in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Nullable<decimal> GrossAmount
        {
            get
            {
                return this._GrossAmount;
            }
            set
            {
                this.OnGrossAmountChanging(value);
                this._GrossAmount = value;
                this.OnGrossAmountChanged();
                this.OnPropertyChanged("GrossAmount");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Nullable<decimal> _GrossAmount;
        partial void OnGrossAmountChanging(global::System.Nullable<decimal> value);
        partial void OnGrossAmountChanged();
        /// <summary>
        /// There are no comments for Property GrossAmountExt in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Nullable<decimal> GrossAmountExt
        {
            get
            {
                return this._GrossAmountExt;
            }
            set
            {
                this.OnGrossAmountExtChanging(value);
                this._GrossAmountExt = value;
                this.OnGrossAmountExtChanged();
                this.OnPropertyChanged("GrossAmountExt");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Nullable<decimal> _GrossAmountExt;
        partial void OnGrossAmountExtChanging(global::System.Nullable<decimal> value);
        partial void OnGrossAmountExtChanged();
        /// <summary>
        /// There are no comments for Property NetAmount in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Nullable<decimal> NetAmount
        {
            get
            {
                return this._NetAmount;
            }
            set
            {
                this.OnNetAmountChanging(value);
                this._NetAmount = value;
                this.OnNetAmountChanged();
                this.OnPropertyChanged("NetAmount");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Nullable<decimal> _NetAmount;
        partial void OnNetAmountChanging(global::System.Nullable<decimal> value);
        partial void OnNetAmountChanged();
        /// <summary>
        /// There are no comments for Property NetAmountExt in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Nullable<decimal> NetAmountExt
        {
            get
            {
                return this._NetAmountExt;
            }
            set
            {
                this.OnNetAmountExtChanging(value);
                this._NetAmountExt = value;
                this.OnNetAmountExtChanged();
                this.OnPropertyChanged("NetAmountExt");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Nullable<decimal> _NetAmountExt;
        partial void OnNetAmountExtChanging(global::System.Nullable<decimal> value);
        partial void OnNetAmountExtChanged();
        /// <summary>
        /// There are no comments for Property TaxAmount in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Nullable<decimal> TaxAmount
        {
            get
            {
                return this._TaxAmount;
            }
            set
            {
                this.OnTaxAmountChanging(value);
                this._TaxAmount = value;
                this.OnTaxAmountChanged();
                this.OnPropertyChanged("TaxAmount");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Nullable<decimal> _TaxAmount;
        partial void OnTaxAmountChanging(global::System.Nullable<decimal> value);
        partial void OnTaxAmountChanged();
        /// <summary>
        /// There are no comments for Property TaxAmountExt in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Nullable<decimal> TaxAmountExt
        {
            get
            {
                return this._TaxAmountExt;
            }
            set
            {
                this.OnTaxAmountExtChanging(value);
                this._TaxAmountExt = value;
                this.OnTaxAmountExtChanged();
                this.OnPropertyChanged("TaxAmountExt");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Nullable<decimal> _TaxAmountExt;
        partial void OnTaxAmountExtChanging(global::System.Nullable<decimal> value);
        partial void OnTaxAmountExtChanged();
        /// <summary>
        /// There are no comments for Property DeliveryDate in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Nullable<global::System.DateTime> DeliveryDate
        {
            get
            {
                return this._DeliveryDate;
            }
            set
            {
                this.OnDeliveryDateChanging(value);
                this._DeliveryDate = value;
                this.OnDeliveryDateChanged();
                this.OnPropertyChanged("DeliveryDate");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Nullable<global::System.DateTime> _DeliveryDate;
        partial void OnDeliveryDateChanging(global::System.Nullable<global::System.DateTime> value);
        partial void OnDeliveryDateChanged();
        /// <summary>
        /// There are no comments for Property Quantity in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Nullable<decimal> Quantity
        {
            get
            {
                return this._Quantity;
            }
            set
            {
                this.OnQuantityChanging(value);
                this._Quantity = value;
                this.OnQuantityChanged();
                this.OnPropertyChanged("Quantity");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Nullable<decimal> _Quantity;
        partial void OnQuantityChanging(global::System.Nullable<decimal> value);
        partial void OnQuantityChanged();
        /// <summary>
        /// There are no comments for Property QuantityUnit in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string QuantityUnit
        {
            get
            {
                return this._QuantityUnit;
            }
            set
            {
                this.OnQuantityUnitChanging(value);
                this._QuantityUnit = value;
                this.OnQuantityUnitChanged();
                this.OnPropertyChanged("QuantityUnit");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _QuantityUnit;
        partial void OnQuantityUnitChanging(string value);
        partial void OnQuantityUnitChanged();
        /// <summary>
        /// There are no comments for Product in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public Product Product
        {
            get
            {
                return this._Product;
            }
            set
            {
                this._Product = value;
                this.OnPropertyChanged("Product");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private Product _Product;
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public event global::System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        protected virtual void OnPropertyChanged(string property)
        {
            if ((this.PropertyChanged != null))
            {
                this.PropertyChanged(this, new global::System.ComponentModel.PropertyChangedEventArgs(property));
            }
        }
    }
    /// <summary>
    /// There are no comments for ZGWSAMPLE_SRV.BusinessPartner in the schema.
    /// </summary>
    /// <KeyProperties>
    /// BusinessPartnerID
    /// </KeyProperties>
    [global::System.Data.Services.Common.EntitySetAttribute("BusinessPartnerCollection")]
    [global::System.Data.Services.Common.DataServiceKeyAttribute("BusinessPartnerID")]
    public partial class BusinessPartner : global::System.ComponentModel.INotifyPropertyChanged
    {
        /// <summary>
        /// Create a new BusinessPartner object.
        /// </summary>
        /// <param name="businessPartnerID">Initial value of BusinessPartnerID.</param>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public static BusinessPartner CreateBusinessPartner(string businessPartnerID)
        {
            BusinessPartner businessPartner = new BusinessPartner();
            businessPartner.BusinessPartnerID = businessPartnerID;
            return businessPartner;
        }
        /// <summary>
        /// There are no comments for Property BusinessPartnerID in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string BusinessPartnerID
        {
            get
            {
                return this._BusinessPartnerID;
            }
            set
            {
                this.OnBusinessPartnerIDChanging(value);
                this._BusinessPartnerID = value;
                this.OnBusinessPartnerIDChanged();
                this.OnPropertyChanged("BusinessPartnerID");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _BusinessPartnerID;
        partial void OnBusinessPartnerIDChanging(string value);
        partial void OnBusinessPartnerIDChanged();
        /// <summary>
        /// There are no comments for Property BpRole in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string BpRole
        {
            get
            {
                return this._BpRole;
            }
            set
            {
                this.OnBpRoleChanging(value);
                this._BpRole = value;
                this.OnBpRoleChanged();
                this.OnPropertyChanged("BpRole");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _BpRole;
        partial void OnBpRoleChanging(string value);
        partial void OnBpRoleChanged();
        /// <summary>
        /// There are no comments for Property EmailAddress in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string EmailAddress
        {
            get
            {
                return this._EmailAddress;
            }
            set
            {
                this.OnEmailAddressChanging(value);
                this._EmailAddress = value;
                this.OnEmailAddressChanged();
                this.OnPropertyChanged("EmailAddress");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _EmailAddress;
        partial void OnEmailAddressChanging(string value);
        partial void OnEmailAddressChanged();
        /// <summary>
        /// There are no comments for Property PhoneNumber in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string PhoneNumber
        {
            get
            {
                return this._PhoneNumber;
            }
            set
            {
                this.OnPhoneNumberChanging(value);
                this._PhoneNumber = value;
                this.OnPhoneNumberChanged();
                this.OnPropertyChanged("PhoneNumber");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _PhoneNumber;
        partial void OnPhoneNumberChanging(string value);
        partial void OnPhoneNumberChanged();
        /// <summary>
        /// There are no comments for Property FaxNumber in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string FaxNumber
        {
            get
            {
                return this._FaxNumber;
            }
            set
            {
                this.OnFaxNumberChanging(value);
                this._FaxNumber = value;
                this.OnFaxNumberChanged();
                this.OnPropertyChanged("FaxNumber");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _FaxNumber;
        partial void OnFaxNumberChanging(string value);
        partial void OnFaxNumberChanged();
        /// <summary>
        /// There are no comments for Property WebAddress in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string WebAddress
        {
            get
            {
                return this._WebAddress;
            }
            set
            {
                this.OnWebAddressChanging(value);
                this._WebAddress = value;
                this.OnWebAddressChanged();
                this.OnPropertyChanged("WebAddress");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _WebAddress;
        partial void OnWebAddressChanging(string value);
        partial void OnWebAddressChanged();
        /// <summary>
        /// There are no comments for Property CompanyName in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string CompanyName
        {
            get
            {
                return this._CompanyName;
            }
            set
            {
                this.OnCompanyNameChanging(value);
                this._CompanyName = value;
                this.OnCompanyNameChanged();
                this.OnPropertyChanged("CompanyName");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _CompanyName;
        partial void OnCompanyNameChanging(string value);
        partial void OnCompanyNameChanged();
        /// <summary>
        /// There are no comments for Property LegalForm in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string LegalForm
        {
            get
            {
                return this._LegalForm;
            }
            set
            {
                this.OnLegalFormChanging(value);
                this._LegalForm = value;
                this.OnLegalFormChanged();
                this.OnPropertyChanged("LegalForm");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _LegalForm;
        partial void OnLegalFormChanging(string value);
        partial void OnLegalFormChanged();
        /// <summary>
        /// There are no comments for Property CurrencyCode in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string CurrencyCode
        {
            get
            {
                return this._CurrencyCode;
            }
            set
            {
                this.OnCurrencyCodeChanging(value);
                this._CurrencyCode = value;
                this.OnCurrencyCodeChanged();
                this.OnPropertyChanged("CurrencyCode");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _CurrencyCode;
        partial void OnCurrencyCodeChanging(string value);
        partial void OnCurrencyCodeChanged();
        /// <summary>
        /// There are no comments for Property City in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string City
        {
            get
            {
                return this._City;
            }
            set
            {
                this.OnCityChanging(value);
                this._City = value;
                this.OnCityChanged();
                this.OnPropertyChanged("City");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _City;
        partial void OnCityChanging(string value);
        partial void OnCityChanged();
        /// <summary>
        /// There are no comments for Property PostalCode in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string PostalCode
        {
            get
            {
                return this._PostalCode;
            }
            set
            {
                this.OnPostalCodeChanging(value);
                this._PostalCode = value;
                this.OnPostalCodeChanged();
                this.OnPropertyChanged("PostalCode");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _PostalCode;
        partial void OnPostalCodeChanging(string value);
        partial void OnPostalCodeChanged();
        /// <summary>
        /// There are no comments for Property Street in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Street
        {
            get
            {
                return this._Street;
            }
            set
            {
                this.OnStreetChanging(value);
                this._Street = value;
                this.OnStreetChanged();
                this.OnPropertyChanged("Street");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Street;
        partial void OnStreetChanging(string value);
        partial void OnStreetChanged();
        /// <summary>
        /// There are no comments for Property Building in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Building
        {
            get
            {
                return this._Building;
            }
            set
            {
                this.OnBuildingChanging(value);
                this._Building = value;
                this.OnBuildingChanged();
                this.OnPropertyChanged("Building");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Building;
        partial void OnBuildingChanging(string value);
        partial void OnBuildingChanged();
        /// <summary>
        /// There are no comments for Property Country in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Country
        {
            get
            {
                return this._Country;
            }
            set
            {
                this.OnCountryChanging(value);
                this._Country = value;
                this.OnCountryChanged();
                this.OnPropertyChanged("Country");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Country;
        partial void OnCountryChanging(string value);
        partial void OnCountryChanged();
        /// <summary>
        /// There are no comments for Property AddressType in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string AddressType
        {
            get
            {
                return this._AddressType;
            }
            set
            {
                this.OnAddressTypeChanging(value);
                this._AddressType = value;
                this.OnAddressTypeChanged();
                this.OnPropertyChanged("AddressType");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _AddressType;
        partial void OnAddressTypeChanging(string value);
        partial void OnAddressTypeChanged();
        /// <summary>
        /// There are no comments for Property AddressValStartDate in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Nullable<global::System.DateTime> AddressValStartDate
        {
            get
            {
                return this._AddressValStartDate;
            }
            set
            {
                this.OnAddressValStartDateChanging(value);
                this._AddressValStartDate = value;
                this.OnAddressValStartDateChanged();
                this.OnPropertyChanged("AddressValStartDate");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Nullable<global::System.DateTime> _AddressValStartDate;
        partial void OnAddressValStartDateChanging(global::System.Nullable<global::System.DateTime> value);
        partial void OnAddressValStartDateChanged();
        /// <summary>
        /// There are no comments for Property AddressValEndDate in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Nullable<global::System.DateTime> AddressValEndDate
        {
            get
            {
                return this._AddressValEndDate;
            }
            set
            {
                this.OnAddressValEndDateChanging(value);
                this._AddressValEndDate = value;
                this.OnAddressValEndDateChanged();
                this.OnPropertyChanged("AddressValEndDate");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Nullable<global::System.DateTime> _AddressValEndDate;
        partial void OnAddressValEndDateChanging(global::System.Nullable<global::System.DateTime> value);
        partial void OnAddressValEndDateChanged();
        /// <summary>
        /// There are no comments for Property CreatedBy in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string CreatedBy
        {
            get
            {
                return this._CreatedBy;
            }
            set
            {
                this.OnCreatedByChanging(value);
                this._CreatedBy = value;
                this.OnCreatedByChanged();
                this.OnPropertyChanged("CreatedBy");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _CreatedBy;
        partial void OnCreatedByChanging(string value);
        partial void OnCreatedByChanged();
        /// <summary>
        /// There are no comments for Property CreatedAt in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Nullable<global::System.DateTime> CreatedAt
        {
            get
            {
                return this._CreatedAt;
            }
            set
            {
                this.OnCreatedAtChanging(value);
                this._CreatedAt = value;
                this.OnCreatedAtChanged();
                this.OnPropertyChanged("CreatedAt");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Nullable<global::System.DateTime> _CreatedAt;
        partial void OnCreatedAtChanging(global::System.Nullable<global::System.DateTime> value);
        partial void OnCreatedAtChanged();
        /// <summary>
        /// There are no comments for Property ChangedBy in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string ChangedBy
        {
            get
            {
                return this._ChangedBy;
            }
            set
            {
                this.OnChangedByChanging(value);
                this._ChangedBy = value;
                this.OnChangedByChanged();
                this.OnPropertyChanged("ChangedBy");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _ChangedBy;
        partial void OnChangedByChanging(string value);
        partial void OnChangedByChanged();
        /// <summary>
        /// There are no comments for Property ChangedAt in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Nullable<global::System.DateTime> ChangedAt
        {
            get
            {
                return this._ChangedAt;
            }
            set
            {
                this.OnChangedAtChanging(value);
                this._ChangedAt = value;
                this.OnChangedAtChanged();
                this.OnPropertyChanged("ChangedAt");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Nullable<global::System.DateTime> _ChangedAt;
        partial void OnChangedAtChanging(global::System.Nullable<global::System.DateTime> value);
        partial void OnChangedAtChanged();
        /// <summary>
        /// There are no comments for SalesOrders in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceCollection<SalesOrder> SalesOrders
        {
            get
            {
                return this._SalesOrders;
            }
            set
            {
                this._SalesOrders = value;
                this.OnPropertyChanged("SalesOrders");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceCollection<SalesOrder> _SalesOrders = new global::System.Data.Services.Client.DataServiceCollection<SalesOrder>(null, System.Data.Services.Client.TrackingMode.None);
        /// <summary>
        /// There are no comments for Contacts in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceCollection<Contact> Contacts
        {
            get
            {
                return this._Contacts;
            }
            set
            {
                this._Contacts = value;
                this.OnPropertyChanged("Contacts");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceCollection<Contact> _Contacts = new global::System.Data.Services.Client.DataServiceCollection<Contact>(null, System.Data.Services.Client.TrackingMode.None);
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public event global::System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        protected virtual void OnPropertyChanged(string property)
        {
            if ((this.PropertyChanged != null))
            {
                this.PropertyChanged(this, new global::System.ComponentModel.PropertyChangedEventArgs(property));
            }
        }
    }
    /// <summary>
    /// There are no comments for ZGWSAMPLE_SRV.Contact in the schema.
    /// </summary>
    /// <KeyProperties>
    /// AddressType
    /// Country
    /// Building
    /// Street
    /// City
    /// PostalCode
    /// BusinessPartnerID
    /// Title
    /// FirstName
    /// MiddleName
    /// LastName
    /// </KeyProperties>
    [global::System.Data.Services.Common.EntitySetAttribute("ContactCollection")]
    [global::System.Data.Services.Common.DataServiceKeyAttribute("AddressType", "Country", "Building", "Street", "City", "PostalCode", "BusinessPartnerID", "Title", "FirstName", "MiddleName", "LastName")]
    public partial class Contact : global::System.ComponentModel.INotifyPropertyChanged
    {
        /// <summary>
        /// Create a new Contact object.
        /// </summary>
        /// <param name="addressType">Initial value of AddressType.</param>
        /// <param name="country">Initial value of Country.</param>
        /// <param name="building">Initial value of Building.</param>
        /// <param name="street">Initial value of Street.</param>
        /// <param name="city">Initial value of City.</param>
        /// <param name="postalCode">Initial value of PostalCode.</param>
        /// <param name="businessPartnerID">Initial value of BusinessPartnerID.</param>
        /// <param name="title">Initial value of Title.</param>
        /// <param name="firstName">Initial value of FirstName.</param>
        /// <param name="middleName">Initial value of MiddleName.</param>
        /// <param name="lastName">Initial value of LastName.</param>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public static Contact CreateContact(string addressType, string country, string building, string street, string city, string postalCode, string businessPartnerID, string title, string firstName, string middleName, string lastName)
        {
            Contact contact = new Contact();
            contact.AddressType = addressType;
            contact.Country = country;
            contact.Building = building;
            contact.Street = street;
            contact.City = city;
            contact.PostalCode = postalCode;
            contact.BusinessPartnerID = businessPartnerID;
            contact.Title = title;
            contact.FirstName = firstName;
            contact.MiddleName = middleName;
            contact.LastName = lastName;
            return contact;
        }
        /// <summary>
        /// There are no comments for Property AddressValEndDate in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Nullable<global::System.DateTime> AddressValEndDate
        {
            get
            {
                return this._AddressValEndDate;
            }
            set
            {
                this.OnAddressValEndDateChanging(value);
                this._AddressValEndDate = value;
                this.OnAddressValEndDateChanged();
                this.OnPropertyChanged("AddressValEndDate");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Nullable<global::System.DateTime> _AddressValEndDate;
        partial void OnAddressValEndDateChanging(global::System.Nullable<global::System.DateTime> value);
        partial void OnAddressValEndDateChanged();
        /// <summary>
        /// There are no comments for Property AddressValStartDate in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Nullable<global::System.DateTime> AddressValStartDate
        {
            get
            {
                return this._AddressValStartDate;
            }
            set
            {
                this.OnAddressValStartDateChanging(value);
                this._AddressValStartDate = value;
                this.OnAddressValStartDateChanged();
                this.OnPropertyChanged("AddressValStartDate");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Nullable<global::System.DateTime> _AddressValStartDate;
        partial void OnAddressValStartDateChanging(global::System.Nullable<global::System.DateTime> value);
        partial void OnAddressValStartDateChanged();
        /// <summary>
        /// There are no comments for Property AddressType in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string AddressType
        {
            get
            {
                return this._AddressType;
            }
            set
            {
                this.OnAddressTypeChanging(value);
                this._AddressType = value;
                this.OnAddressTypeChanged();
                this.OnPropertyChanged("AddressType");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _AddressType;
        partial void OnAddressTypeChanging(string value);
        partial void OnAddressTypeChanged();
        /// <summary>
        /// There are no comments for Property Country in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Country
        {
            get
            {
                return this._Country;
            }
            set
            {
                this.OnCountryChanging(value);
                this._Country = value;
                this.OnCountryChanged();
                this.OnPropertyChanged("Country");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Country;
        partial void OnCountryChanging(string value);
        partial void OnCountryChanged();
        /// <summary>
        /// There are no comments for Property Building in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Building
        {
            get
            {
                return this._Building;
            }
            set
            {
                this.OnBuildingChanging(value);
                this._Building = value;
                this.OnBuildingChanged();
                this.OnPropertyChanged("Building");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Building;
        partial void OnBuildingChanging(string value);
        partial void OnBuildingChanged();
        /// <summary>
        /// There are no comments for Property Street in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Street
        {
            get
            {
                return this._Street;
            }
            set
            {
                this.OnStreetChanging(value);
                this._Street = value;
                this.OnStreetChanged();
                this.OnPropertyChanged("Street");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Street;
        partial void OnStreetChanging(string value);
        partial void OnStreetChanged();
        /// <summary>
        /// There are no comments for Property City in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string City
        {
            get
            {
                return this._City;
            }
            set
            {
                this.OnCityChanging(value);
                this._City = value;
                this.OnCityChanged();
                this.OnPropertyChanged("City");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _City;
        partial void OnCityChanging(string value);
        partial void OnCityChanged();
        /// <summary>
        /// There are no comments for Property PostalCode in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string PostalCode
        {
            get
            {
                return this._PostalCode;
            }
            set
            {
                this.OnPostalCodeChanging(value);
                this._PostalCode = value;
                this.OnPostalCodeChanged();
                this.OnPropertyChanged("PostalCode");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _PostalCode;
        partial void OnPostalCodeChanging(string value);
        partial void OnPostalCodeChanged();
        /// <summary>
        /// There are no comments for Property BusinessPartnerID in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string BusinessPartnerID
        {
            get
            {
                return this._BusinessPartnerID;
            }
            set
            {
                this.OnBusinessPartnerIDChanging(value);
                this._BusinessPartnerID = value;
                this.OnBusinessPartnerIDChanged();
                this.OnPropertyChanged("BusinessPartnerID");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _BusinessPartnerID;
        partial void OnBusinessPartnerIDChanging(string value);
        partial void OnBusinessPartnerIDChanged();
        /// <summary>
        /// There are no comments for Property Title in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Title
        {
            get
            {
                return this._Title;
            }
            set
            {
                this.OnTitleChanging(value);
                this._Title = value;
                this.OnTitleChanged();
                this.OnPropertyChanged("Title");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Title;
        partial void OnTitleChanging(string value);
        partial void OnTitleChanged();
        /// <summary>
        /// There are no comments for Property FirstName in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string FirstName
        {
            get
            {
                return this._FirstName;
            }
            set
            {
                this.OnFirstNameChanging(value);
                this._FirstName = value;
                this.OnFirstNameChanged();
                this.OnPropertyChanged("FirstName");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _FirstName;
        partial void OnFirstNameChanging(string value);
        partial void OnFirstNameChanged();
        /// <summary>
        /// There are no comments for Property Language in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Language
        {
            get
            {
                return this._Language;
            }
            set
            {
                this.OnLanguageChanging(value);
                this._Language = value;
                this.OnLanguageChanged();
                this.OnPropertyChanged("Language");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Language;
        partial void OnLanguageChanging(string value);
        partial void OnLanguageChanged();
        /// <summary>
        /// There are no comments for Property MiddleName in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string MiddleName
        {
            get
            {
                return this._MiddleName;
            }
            set
            {
                this.OnMiddleNameChanging(value);
                this._MiddleName = value;
                this.OnMiddleNameChanged();
                this.OnPropertyChanged("MiddleName");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _MiddleName;
        partial void OnMiddleNameChanging(string value);
        partial void OnMiddleNameChanged();
        /// <summary>
        /// There are no comments for Property LastName in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string LastName
        {
            get
            {
                return this._LastName;
            }
            set
            {
                this.OnLastNameChanging(value);
                this._LastName = value;
                this.OnLastNameChanged();
                this.OnPropertyChanged("LastName");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _LastName;
        partial void OnLastNameChanging(string value);
        partial void OnLastNameChanged();
        /// <summary>
        /// There are no comments for Property Nickname in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Nickname
        {
            get
            {
                return this._Nickname;
            }
            set
            {
                this.OnNicknameChanging(value);
                this._Nickname = value;
                this.OnNicknameChanged();
                this.OnPropertyChanged("Nickname");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Nickname;
        partial void OnNicknameChanging(string value);
        partial void OnNicknameChanged();
        /// <summary>
        /// There are no comments for Property EmailAddress in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string EmailAddress
        {
            get
            {
                return this._EmailAddress;
            }
            set
            {
                this.OnEmailAddressChanging(value);
                this._EmailAddress = value;
                this.OnEmailAddressChanged();
                this.OnPropertyChanged("EmailAddress");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _EmailAddress;
        partial void OnEmailAddressChanging(string value);
        partial void OnEmailAddressChanged();
        /// <summary>
        /// There are no comments for Property Initials in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Initials
        {
            get
            {
                return this._Initials;
            }
            set
            {
                this.OnInitialsChanging(value);
                this._Initials = value;
                this.OnInitialsChanged();
                this.OnPropertyChanged("Initials");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Initials;
        partial void OnInitialsChanging(string value);
        partial void OnInitialsChanged();
        /// <summary>
        /// There are no comments for Property Sex in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Sex
        {
            get
            {
                return this._Sex;
            }
            set
            {
                this.OnSexChanging(value);
                this._Sex = value;
                this.OnSexChanged();
                this.OnPropertyChanged("Sex");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Sex;
        partial void OnSexChanging(string value);
        partial void OnSexChanged();
        /// <summary>
        /// There are no comments for Property PhoneNumber in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string PhoneNumber
        {
            get
            {
                return this._PhoneNumber;
            }
            set
            {
                this.OnPhoneNumberChanging(value);
                this._PhoneNumber = value;
                this.OnPhoneNumberChanged();
                this.OnPropertyChanged("PhoneNumber");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _PhoneNumber;
        partial void OnPhoneNumberChanging(string value);
        partial void OnPhoneNumberChanged();
        /// <summary>
        /// There are no comments for Property FaxNumber in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string FaxNumber
        {
            get
            {
                return this._FaxNumber;
            }
            set
            {
                this.OnFaxNumberChanging(value);
                this._FaxNumber = value;
                this.OnFaxNumberChanged();
                this.OnPropertyChanged("FaxNumber");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _FaxNumber;
        partial void OnFaxNumberChanging(string value);
        partial void OnFaxNumberChanged();
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public event global::System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        protected virtual void OnPropertyChanged(string property)
        {
            if ((this.PropertyChanged != null))
            {
                this.PropertyChanged(this, new global::System.ComponentModel.PropertyChangedEventArgs(property));
            }
        }
    }
    /// <summary>
    /// There are no comments for ZGWSAMPLE_SRV.SalesOrder in the schema.
    /// </summary>
    /// <KeyProperties>
    /// SoId
    /// </KeyProperties>
    [global::System.Data.Services.Common.EntitySetAttribute("SalesOrderCollection")]
    [global::System.Data.Services.Common.DataServiceKeyAttribute("SoId")]
    public partial class SalesOrder : global::System.ComponentModel.INotifyPropertyChanged
    {
        /// <summary>
        /// Create a new SalesOrder object.
        /// </summary>
        /// <param name="soId">Initial value of SoId.</param>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public static SalesOrder CreateSalesOrder(string soId)
        {
            SalesOrder salesOrder = new SalesOrder();
            salesOrder.SoId = soId;
            return salesOrder;
        }
        /// <summary>
        /// There are no comments for Property LifecycleStatus in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string LifecycleStatus
        {
            get
            {
                return this._LifecycleStatus;
            }
            set
            {
                this.OnLifecycleStatusChanging(value);
                this._LifecycleStatus = value;
                this.OnLifecycleStatusChanged();
                this.OnPropertyChanged("LifecycleStatus");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _LifecycleStatus;
        partial void OnLifecycleStatusChanging(string value);
        partial void OnLifecycleStatusChanged();
        /// <summary>
        /// There are no comments for Property TaxAmountExt in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Nullable<decimal> TaxAmountExt
        {
            get
            {
                return this._TaxAmountExt;
            }
            set
            {
                this.OnTaxAmountExtChanging(value);
                this._TaxAmountExt = value;
                this.OnTaxAmountExtChanged();
                this.OnPropertyChanged("TaxAmountExt");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Nullable<decimal> _TaxAmountExt;
        partial void OnTaxAmountExtChanging(global::System.Nullable<decimal> value);
        partial void OnTaxAmountExtChanged();
        /// <summary>
        /// There are no comments for Property TaxAmount in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Nullable<decimal> TaxAmount
        {
            get
            {
                return this._TaxAmount;
            }
            set
            {
                this.OnTaxAmountChanging(value);
                this._TaxAmount = value;
                this.OnTaxAmountChanged();
                this.OnPropertyChanged("TaxAmount");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Nullable<decimal> _TaxAmount;
        partial void OnTaxAmountChanging(global::System.Nullable<decimal> value);
        partial void OnTaxAmountChanged();
        /// <summary>
        /// There are no comments for Property NetAmountExt in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Nullable<decimal> NetAmountExt
        {
            get
            {
                return this._NetAmountExt;
            }
            set
            {
                this.OnNetAmountExtChanging(value);
                this._NetAmountExt = value;
                this.OnNetAmountExtChanged();
                this.OnPropertyChanged("NetAmountExt");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Nullable<decimal> _NetAmountExt;
        partial void OnNetAmountExtChanging(global::System.Nullable<decimal> value);
        partial void OnNetAmountExtChanged();
        /// <summary>
        /// There are no comments for Property NetAmount in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Nullable<decimal> NetAmount
        {
            get
            {
                return this._NetAmount;
            }
            set
            {
                this.OnNetAmountChanging(value);
                this._NetAmount = value;
                this.OnNetAmountChanged();
                this.OnPropertyChanged("NetAmount");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Nullable<decimal> _NetAmount;
        partial void OnNetAmountChanging(global::System.Nullable<decimal> value);
        partial void OnNetAmountChanged();
        /// <summary>
        /// There are no comments for Property GrossAmountExt in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Nullable<decimal> GrossAmountExt
        {
            get
            {
                return this._GrossAmountExt;
            }
            set
            {
                this.OnGrossAmountExtChanging(value);
                this._GrossAmountExt = value;
                this.OnGrossAmountExtChanged();
                this.OnPropertyChanged("GrossAmountExt");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Nullable<decimal> _GrossAmountExt;
        partial void OnGrossAmountExtChanging(global::System.Nullable<decimal> value);
        partial void OnGrossAmountExtChanged();
        /// <summary>
        /// There are no comments for Property GrossAmount in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Nullable<decimal> GrossAmount
        {
            get
            {
                return this._GrossAmount;
            }
            set
            {
                this.OnGrossAmountChanging(value);
                this._GrossAmount = value;
                this.OnGrossAmountChanged();
                this.OnPropertyChanged("GrossAmount");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Nullable<decimal> _GrossAmount;
        partial void OnGrossAmountChanging(global::System.Nullable<decimal> value);
        partial void OnGrossAmountChanged();
        /// <summary>
        /// There are no comments for Property CurrencyCode in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string CurrencyCode
        {
            get
            {
                return this._CurrencyCode;
            }
            set
            {
                this.OnCurrencyCodeChanging(value);
                this._CurrencyCode = value;
                this.OnCurrencyCodeChanged();
                this.OnPropertyChanged("CurrencyCode");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _CurrencyCode;
        partial void OnCurrencyCodeChanging(string value);
        partial void OnCurrencyCodeChanged();
        /// <summary>
        /// There are no comments for Property BuyerName in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string BuyerName
        {
            get
            {
                return this._BuyerName;
            }
            set
            {
                this.OnBuyerNameChanging(value);
                this._BuyerName = value;
                this.OnBuyerNameChanged();
                this.OnPropertyChanged("BuyerName");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _BuyerName;
        partial void OnBuyerNameChanging(string value);
        partial void OnBuyerNameChanged();
        /// <summary>
        /// There are no comments for Property BuyerId in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string BuyerId
        {
            get
            {
                return this._BuyerId;
            }
            set
            {
                this.OnBuyerIdChanging(value);
                this._BuyerId = value;
                this.OnBuyerIdChanged();
                this.OnPropertyChanged("BuyerId");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _BuyerId;
        partial void OnBuyerIdChanging(string value);
        partial void OnBuyerIdChanged();
        /// <summary>
        /// There are no comments for Property Note in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Note
        {
            get
            {
                return this._Note;
            }
            set
            {
                this.OnNoteChanging(value);
                this._Note = value;
                this.OnNoteChanged();
                this.OnPropertyChanged("Note");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Note;
        partial void OnNoteChanging(string value);
        partial void OnNoteChanged();
        /// <summary>
        /// There are no comments for Property ChangedByBp in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string ChangedByBp
        {
            get
            {
                return this._ChangedByBp;
            }
            set
            {
                this.OnChangedByBpChanging(value);
                this._ChangedByBp = value;
                this.OnChangedByBpChanged();
                this.OnPropertyChanged("ChangedByBp");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _ChangedByBp;
        partial void OnChangedByBpChanging(string value);
        partial void OnChangedByBpChanged();
        /// <summary>
        /// There are no comments for Property CreatedByBp in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string CreatedByBp
        {
            get
            {
                return this._CreatedByBp;
            }
            set
            {
                this.OnCreatedByBpChanging(value);
                this._CreatedByBp = value;
                this.OnCreatedByBpChanged();
                this.OnPropertyChanged("CreatedByBp");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _CreatedByBp;
        partial void OnCreatedByBpChanging(string value);
        partial void OnCreatedByBpChanged();
        /// <summary>
        /// There are no comments for Property ChangedAt in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Nullable<global::System.DateTime> ChangedAt
        {
            get
            {
                return this._ChangedAt;
            }
            set
            {
                this.OnChangedAtChanging(value);
                this._ChangedAt = value;
                this.OnChangedAtChanged();
                this.OnPropertyChanged("ChangedAt");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Nullable<global::System.DateTime> _ChangedAt;
        partial void OnChangedAtChanging(global::System.Nullable<global::System.DateTime> value);
        partial void OnChangedAtChanged();
        /// <summary>
        /// There are no comments for Property ChangedBy in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string ChangedBy
        {
            get
            {
                return this._ChangedBy;
            }
            set
            {
                this.OnChangedByChanging(value);
                this._ChangedBy = value;
                this.OnChangedByChanged();
                this.OnPropertyChanged("ChangedBy");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _ChangedBy;
        partial void OnChangedByChanging(string value);
        partial void OnChangedByChanged();
        /// <summary>
        /// There are no comments for Property CreatedAt in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Nullable<global::System.DateTime> CreatedAt
        {
            get
            {
                return this._CreatedAt;
            }
            set
            {
                this.OnCreatedAtChanging(value);
                this._CreatedAt = value;
                this.OnCreatedAtChanged();
                this.OnPropertyChanged("CreatedAt");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Nullable<global::System.DateTime> _CreatedAt;
        partial void OnCreatedAtChanging(global::System.Nullable<global::System.DateTime> value);
        partial void OnCreatedAtChanged();
        /// <summary>
        /// There are no comments for Property CreatedBy in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string CreatedBy
        {
            get
            {
                return this._CreatedBy;
            }
            set
            {
                this.OnCreatedByChanging(value);
                this._CreatedBy = value;
                this.OnCreatedByChanged();
                this.OnPropertyChanged("CreatedBy");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _CreatedBy;
        partial void OnCreatedByChanging(string value);
        partial void OnCreatedByChanged();
        /// <summary>
        /// There are no comments for Property SoId in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string SoId
        {
            get
            {
                return this._SoId;
            }
            set
            {
                this.OnSoIdChanging(value);
                this._SoId = value;
                this.OnSoIdChanged();
                this.OnPropertyChanged("SoId");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _SoId;
        partial void OnSoIdChanging(string value);
        partial void OnSoIdChanged();
        /// <summary>
        /// There are no comments for Property BillingStatus in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string BillingStatus
        {
            get
            {
                return this._BillingStatus;
            }
            set
            {
                this.OnBillingStatusChanging(value);
                this._BillingStatus = value;
                this.OnBillingStatusChanged();
                this.OnPropertyChanged("BillingStatus");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _BillingStatus;
        partial void OnBillingStatusChanging(string value);
        partial void OnBillingStatusChanged();
        /// <summary>
        /// There are no comments for Property DeliveryStatus in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string DeliveryStatus
        {
            get
            {
                return this._DeliveryStatus;
            }
            set
            {
                this.OnDeliveryStatusChanging(value);
                this._DeliveryStatus = value;
                this.OnDeliveryStatusChanged();
                this.OnPropertyChanged("DeliveryStatus");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _DeliveryStatus;
        partial void OnDeliveryStatusChanging(string value);
        partial void OnDeliveryStatusChanged();
        /// <summary>
        /// There are no comments for LineItems in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceCollection<SalesOrderLineItem> LineItems
        {
            get
            {
                return this._LineItems;
            }
            set
            {
                this._LineItems = value;
                this.OnPropertyChanged("LineItems");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceCollection<SalesOrderLineItem> _LineItems = new global::System.Data.Services.Client.DataServiceCollection<SalesOrderLineItem>(null, System.Data.Services.Client.TrackingMode.None);
        /// <summary>
        /// There are no comments for BusinessPartner in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public BusinessPartner BusinessPartner
        {
            get
            {
                return this._BusinessPartner;
            }
            set
            {
                this._BusinessPartner = value;
                this.OnPropertyChanged("BusinessPartner");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private BusinessPartner _BusinessPartner;
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public event global::System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        protected virtual void OnPropertyChanged(string property)
        {
            if ((this.PropertyChanged != null))
            {
                this.PropertyChanged(this, new global::System.ComponentModel.PropertyChangedEventArgs(property));
            }
        }
    }
    /// <summary>
    /// There are no comments for ZGWSAMPLE_SRV.Product in the schema.
    /// </summary>
    /// <KeyProperties>
    /// ProductId
    /// </KeyProperties>
    [global::System.Data.Services.Common.EntitySetAttribute("ProductCollection")]
    [global::System.Data.Services.Common.DataServiceKeyAttribute("ProductId")]
    public partial class Product : global::System.ComponentModel.INotifyPropertyChanged
    {
        /// <summary>
        /// Create a new Product object.
        /// </summary>
        /// <param name="productId">Initial value of ProductId.</param>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public static Product CreateProduct(string productId)
        {
            Product product = new Product();
            product.ProductId = productId;
            return product;
        }
        /// <summary>
        /// There are no comments for Property ProductId in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string ProductId
        {
            get
            {
                return this._ProductId;
            }
            set
            {
                this.OnProductIdChanging(value);
                this._ProductId = value;
                this.OnProductIdChanged();
                this.OnPropertyChanged("ProductId");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _ProductId;
        partial void OnProductIdChanging(string value);
        partial void OnProductIdChanged();
        /// <summary>
        /// There are no comments for Property TypeCode in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string TypeCode
        {
            get
            {
                return this._TypeCode;
            }
            set
            {
                this.OnTypeCodeChanging(value);
                this._TypeCode = value;
                this.OnTypeCodeChanged();
                this.OnPropertyChanged("TypeCode");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _TypeCode;
        partial void OnTypeCodeChanging(string value);
        partial void OnTypeCodeChanged();
        /// <summary>
        /// There are no comments for Property Category in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Category
        {
            get
            {
                return this._Category;
            }
            set
            {
                this.OnCategoryChanging(value);
                this._Category = value;
                this.OnCategoryChanged();
                this.OnPropertyChanged("Category");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Category;
        partial void OnCategoryChanging(string value);
        partial void OnCategoryChanged();
        /// <summary>
        /// There are no comments for Property Name in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Name
        {
            get
            {
                return this._Name;
            }
            set
            {
                this.OnNameChanging(value);
                this._Name = value;
                this.OnNameChanged();
                this.OnPropertyChanged("Name");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Name;
        partial void OnNameChanging(string value);
        partial void OnNameChanged();
        /// <summary>
        /// There are no comments for Property Description in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Description
        {
            get
            {
                return this._Description;
            }
            set
            {
                this.OnDescriptionChanging(value);
                this._Description = value;
                this.OnDescriptionChanged();
                this.OnPropertyChanged("Description");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Description;
        partial void OnDescriptionChanging(string value);
        partial void OnDescriptionChanged();
        /// <summary>
        /// There are no comments for Property SupplierId in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string SupplierId
        {
            get
            {
                return this._SupplierId;
            }
            set
            {
                this.OnSupplierIdChanging(value);
                this._SupplierId = value;
                this.OnSupplierIdChanged();
                this.OnPropertyChanged("SupplierId");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _SupplierId;
        partial void OnSupplierIdChanging(string value);
        partial void OnSupplierIdChanged();
        /// <summary>
        /// There are no comments for Property SupplierName in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string SupplierName
        {
            get
            {
                return this._SupplierName;
            }
            set
            {
                this.OnSupplierNameChanging(value);
                this._SupplierName = value;
                this.OnSupplierNameChanged();
                this.OnPropertyChanged("SupplierName");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _SupplierName;
        partial void OnSupplierNameChanging(string value);
        partial void OnSupplierNameChanged();
        /// <summary>
        /// There are no comments for Property TaxTarifCode in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Nullable<byte> TaxTarifCode
        {
            get
            {
                return this._TaxTarifCode;
            }
            set
            {
                this.OnTaxTarifCodeChanging(value);
                this._TaxTarifCode = value;
                this.OnTaxTarifCodeChanged();
                this.OnPropertyChanged("TaxTarifCode");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Nullable<byte> _TaxTarifCode;
        partial void OnTaxTarifCodeChanging(global::System.Nullable<byte> value);
        partial void OnTaxTarifCodeChanged();
        /// <summary>
        /// There are no comments for Property MeasureUnit in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string MeasureUnit
        {
            get
            {
                return this._MeasureUnit;
            }
            set
            {
                this.OnMeasureUnitChanging(value);
                this._MeasureUnit = value;
                this.OnMeasureUnitChanged();
                this.OnPropertyChanged("MeasureUnit");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _MeasureUnit;
        partial void OnMeasureUnitChanging(string value);
        partial void OnMeasureUnitChanged();
        /// <summary>
        /// There are no comments for Property WeightMeasure in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Nullable<decimal> WeightMeasure
        {
            get
            {
                return this._WeightMeasure;
            }
            set
            {
                this.OnWeightMeasureChanging(value);
                this._WeightMeasure = value;
                this.OnWeightMeasureChanged();
                this.OnPropertyChanged("WeightMeasure");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Nullable<decimal> _WeightMeasure;
        partial void OnWeightMeasureChanging(global::System.Nullable<decimal> value);
        partial void OnWeightMeasureChanged();
        /// <summary>
        /// There are no comments for Property WeightUnit in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string WeightUnit
        {
            get
            {
                return this._WeightUnit;
            }
            set
            {
                this.OnWeightUnitChanging(value);
                this._WeightUnit = value;
                this.OnWeightUnitChanged();
                this.OnPropertyChanged("WeightUnit");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _WeightUnit;
        partial void OnWeightUnitChanging(string value);
        partial void OnWeightUnitChanged();
        /// <summary>
        /// There are no comments for Property Price in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Nullable<decimal> Price
        {
            get
            {
                return this._Price;
            }
            set
            {
                this.OnPriceChanging(value);
                this._Price = value;
                this.OnPriceChanged();
                this.OnPropertyChanged("Price");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Nullable<decimal> _Price;
        partial void OnPriceChanging(global::System.Nullable<decimal> value);
        partial void OnPriceChanged();
        /// <summary>
        /// There are no comments for Property CurrencyCode in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string CurrencyCode
        {
            get
            {
                return this._CurrencyCode;
            }
            set
            {
                this.OnCurrencyCodeChanging(value);
                this._CurrencyCode = value;
                this.OnCurrencyCodeChanged();
                this.OnPropertyChanged("CurrencyCode");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _CurrencyCode;
        partial void OnCurrencyCodeChanging(string value);
        partial void OnCurrencyCodeChanged();
        /// <summary>
        /// There are no comments for Property Width in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Nullable<decimal> Width
        {
            get
            {
                return this._Width;
            }
            set
            {
                this.OnWidthChanging(value);
                this._Width = value;
                this.OnWidthChanged();
                this.OnPropertyChanged("Width");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Nullable<decimal> _Width;
        partial void OnWidthChanging(global::System.Nullable<decimal> value);
        partial void OnWidthChanged();
        /// <summary>
        /// There are no comments for Property Depth in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Nullable<decimal> Depth
        {
            get
            {
                return this._Depth;
            }
            set
            {
                this.OnDepthChanging(value);
                this._Depth = value;
                this.OnDepthChanged();
                this.OnPropertyChanged("Depth");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Nullable<decimal> _Depth;
        partial void OnDepthChanging(global::System.Nullable<decimal> value);
        partial void OnDepthChanged();
        /// <summary>
        /// There are no comments for Property Height in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Nullable<decimal> Height
        {
            get
            {
                return this._Height;
            }
            set
            {
                this.OnHeightChanging(value);
                this._Height = value;
                this.OnHeightChanged();
                this.OnPropertyChanged("Height");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Nullable<decimal> _Height;
        partial void OnHeightChanging(global::System.Nullable<decimal> value);
        partial void OnHeightChanged();
        /// <summary>
        /// There are no comments for Property DimUnit in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string DimUnit
        {
            get
            {
                return this._DimUnit;
            }
            set
            {
                this.OnDimUnitChanging(value);
                this._DimUnit = value;
                this.OnDimUnitChanged();
                this.OnPropertyChanged("DimUnit");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _DimUnit;
        partial void OnDimUnitChanging(string value);
        partial void OnDimUnitChanged();
        /// <summary>
        /// There are no comments for Property ProductPicUrl in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string ProductPicUrl
        {
            get
            {
                return this._ProductPicUrl;
            }
            set
            {
                this.OnProductPicUrlChanging(value);
                this._ProductPicUrl = value;
                this.OnProductPicUrlChanged();
                this.OnPropertyChanged("ProductPicUrl");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _ProductPicUrl;
        partial void OnProductPicUrlChanging(string value);
        partial void OnProductPicUrlChanged();
        /// <summary>
        /// There are no comments for Supplier in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public BusinessPartner Supplier
        {
            get
            {
                return this._Supplier;
            }
            set
            {
                this._Supplier = value;
                this.OnPropertyChanged("Supplier");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private BusinessPartner _Supplier;
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public event global::System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        protected virtual void OnPropertyChanged(string property)
        {
            if ((this.PropertyChanged != null))
            {
                this.PropertyChanged(this, new global::System.ComponentModel.PropertyChangedEventArgs(property));
            }
        }
    }
}
